##### Registrar un usuario
POST https://backapijobs-production-ad45.up.railway.app/api/v1/auth/register
Content-Type: application/json

{"email": "gh2dd@gmail.com", "password": "a1b2c3A$"}


##### hacer Login
POST https://backapijobs-production-ad45.up.railway.app/api/v1/auth/login
Content-Type: application/json

{"email": "prueba1@co.co", "password": "a1b2c3A$"}

##### get user information con base ene le token
GET https://backapijobs-production-ad45.up.railway.app/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzaHVsdHoxMkBnbWFpbC5jb20iLCJpYXQiOjE2NzY1NTc0ODksImV4cCI6MTY3NjkxNzQ4OX0.fFoS35TcwwvjmKkid0TG-_OYQvJFOZOoBDiNaeCbT8r0tGhpcHxipqOrQeYNLLH7ONk2pb4pZn8TFBgSGEqhwg
Content-Type: application/json


##### get user information complementary con base ene le token
GET https://backapijobs-production-ad45.up.railway.app/api/v1/user_tecnology
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzaHVsdHoxMkBnbWFpbC5jb20iLCJpYXQiOjE2NzY1NTc0ODksImV4cCI6MTY3NjkxNzQ4OX0.fFoS35TcwwvjmKkid0TG-_OYQvJFOZOoBDiNaeCbT8r0tGhpcHxipqOrQeYNLLH7ONk2pb4pZn8TFBgSGEqhwg
Content-Type: application/json

##### update basic user information complementary con base ene le token
PUT https://backapijobs-production-ad45.up.railway.app/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJwcnVlYmExQGNvLmNvIiwiaWF0IjoxNjc2NTc3NzczLCJleHAiOjE2NzY5Mzc3NzN9.s2FVEUtrnEm_aZ29UvzAMdQVUl_wxwWoMxPehRueRq1-nDEP4iBrI_TflyfHExX9NDTfO7SM8KbGgsc7nBJsdw
Content-Type: application/json

{   
    "firstname": null,
    "lastname": null,
    "about_me": "Informacion que en el diseño",
    "article_1": "Definir que es este campo y donde se captura",
    "age": 45,
    "country": "Venezuela",
    "region": "Miranda",
    "phone": "1234567"
}

### get all users
GET https://backapijobs-production-ad45.up.railway.app/api/v1/users/all
Content-Type: application/json


### get un usuario particular con base en su id
GET https://backapijobs-production-ad45.up.railway.app/api/v1/users/7
Content-Type: application/json

### delete un usuario con base en el token
DELETE https://backapijobs-production-ad45.up.railway.app/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzaHVsdHoxMkBnbWFpbC5jb20iLCJpYXQiOjE2NzY0Njc4NDMsImV4cCI6MTY3NjgyNzg0M30.UCVHS84x1HF5kMbjZbhutOOIo4q9OEbaTohBmNSN-4TTn22wzw8D9dx7_hjpKDvG7VqDVajed80xiY3-zCyIxA
Content-Type: application/json

### requerimiento para los roles y las tecnologias relacionadas
GET https://backapijobs-production-ad45.up.railway.app/api/v1/rol


### Get all Jobs
GET https://backapijobs-production-ad45.up.railway.app/api/v1/jobs?page=0&size=5


### Get un trabajo en particular
GET https://backapijobs-production-ad45.up.railway.app/api/v1/jobs/2

###
GET https://backapijobs-production-ad45.up.railway.app/api/v1/rol

### todas las postulaciones de un usuario
GET https://backapijobs-production-ad45.up.railway.app/api/v1/postulation/user
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzaHVsdHoxMkBnbWFpbC5jb20iLCJpYXQiOjE2NzY0MjU1MTMsImV4cCI6MTY3Njc4NTUxM30.kXVJaLRIe51BgyJsII_X-BL4JLIcI-Gd1FIy9lzZzS0QP5O_x9SglOM496_rXGhBvMYjOEvXtvNZJ4OTSNjCtg
Content-Type: application/json

### todas las tecnologias
GET https://backapijobs-production-ad45.up.railway.app/api/v1/tecnology
Content-Type: application/json

### eliminar una tecnologia
DELETE https://backapijobs-production-ad45.up.railway.app/api/v1/tecnology/6
Content-Type: application/json


### crear tecnologias
POST https://backapijobs-production-ad45.up.railway.app/api/v1/tecnology
Content-Type: application/json

{
"name":"GIMP" 
} 


### crear tecnologia asociada a un rol
POST https://backapijobs-production-ad45.up.railway.app/api/v1/rol_and_tecnology
Content-Type: application/json

{
"rol_id":3,
"tecnology_id":11
} 

