https://jobsapi-wtcn.onrender.com/

### REGISTER => sign up a new user (Hook = useRegister)
POST https://jobsapi-wtcn.onrender.com/api/v1/auth/register
Content-Type: application/json

{"email": "a1@correo.com", "password": "a1a2a3A$"}


### LOGIN => sign in a user (Hook useLogin)
POST https://jobsapi-wtcn.onrender.com/api/v1/auth/login
Content-Type: application/json

{"email": "eliminar@correo.com", "password": "a1a2a3A$"}


### ALL USERS => (Hook = useGetJobSeekers) 
GET https://jobsapi-wtcn.onrender.com/api/v1/users/all
Content-Type: application/json


### GET USER (all information of one user) (Hook = useGetUserbyId)
GET https://jobsapi-wtcn.onrender.com/api/v1/users/5
Content-Type: application/json


### GET USER (all information of one user)
GET https://jobsapi-wtcn.onrender.com/api/v1/users/
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsImVtYWlsIjoianVhbkBjb3JyZW8uY29tIiwiaWF0IjoxNjc2OTg2NzIzLCJleHAiOjE2NzczNDY3MjN9.QudFIJhtnHfa_kkK3mjkBTT_Pf_xQaWwdQWe7aniwvXEyA83H_1cVcdYV6HWz6j-Btg3vdYqt099FeepiPSLlw
Content-Type: application/json


### GET USER complementary information
GET https://backapijobs-production-ad45.up.railway.app/api/v1/user_tecnology
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsImVtYWlsIjoianVhbkBjb3JyZW8uY29tIiwiaWF0IjoxNjc2OTgzMjM0LCJleHAiOjE2NzczNDMyMzR9.LM1ITqHZBIz5reGe6Ep92aoyN5lGREtj4NNqxAGqktfAwUm7taU_7R1kjm-1VnVm1moKdR5h29AkbA-ZjIiMGA
Content-Type: application/json


### DELETE USER using token
DELETE https://jobsapi-wtcn.onrender.com/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJtYXJ0YUBjb3JyZW8uY29tIiwiaWF0IjoxNjc3NjcwMDIyLCJleHAiOjE2NzgwMzAwMjJ9.slguviiSqFDaFD5zGDBQ5h3e7wd1yoUbxubHsBeCf9hWsk1J_LrVl0msRiFbL3J981ERPLKizsb5Pesao41QoA
Content-Type: application/json

### UPDATE USER  basic information using toke
PUT https://jobsapi-wtcn.onrender.com/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTksImVtYWlsIjoiZWxpbWluYXJAY29ycmVvLmNvbSIsImlhdCI6MTY3NzczMDc5MSwiZXhwIjoxNjc4MDkwNzkxfQ.iXbGfa8YrJbXAsnQkwRScQ4-ygGzG-bx6vlfBusEQbdXNV6tlndE5MLMbdEi4Cci0KOSdvR-ON3ZRGQlH5dMfA
Content-Type: application/json

{  
  "avatar" : null,
  "status" : null 
}

### UPDATE USER add new rol to user using token and rol_id y de URL 
POST https://jobsapi-wtcn.onrender.com/api/v1/rol_user/2
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ0dXRhZ3VhcmFkaWdpdGFsQGdtYWlsLmNvbSIsImlhdCI6MTY3NzY4NDA2NywiZXhwIjoxNjc4MDQ0MDY3fQ.yR-b9PVilpdWC4lpQIhvFObYP_fndFmEgoyLZ7IBu-r8Fs6-bUy_TXmv6S6l5E_U1u6n3sRuZ35mj6QzaMG1aQ
Content-Type: application/json

### UPDATE USER add new tecnology to user using token and tecnology_id and year in the URL
POST https://jobsapi-wtcn.onrender.com/api/v1/user_tecnology/4/years/1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ0dXRhZ3VhcmFkaWdpdGFsQGdtYWlsLmNvbSIsImlhdCI6MTY3NzYwMzczMywiZXhwIjoxNjc3OTYzNzMzfQ.WgFeQ3eUqnvA2mykdUoXAfwrk--3mFWhoViKyJ5gm6DNek5q_C5hFPYFRC5KDqf5H_vVAgT5ub9X4gKptpHArw
Content-Type: application/json



### CREATE JOB APPLICATION => postularse para un trabajo

POST https://jobsapi-wtcn.onrender.com/api/v1/postulation/user/job/2
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ0dXRhZ3VhcmFkaWdpdGFsQGdtYWlsLmNvbSIsImlhdCI6MTY3NzYxNTQxMywiZXhwIjoxNjc3OTc1NDEzfQ.yUXkj6fgPNZqnktxXeF6T9SIlkbplnysvSQObVqtW_HYv6Cen1KCPqmw-L7menbb2PXwbzpqtKq7vlKcsLEmMg
Content-Type: application/json





### POST JOBS Create a Job
POST https://jobsapi-wtcn.onrender.com/api/v1/jobs
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ0dXRhZ3VhcmFkaWdpdGFsQGdtYWlsLmNvbSIsImlhdCI6MTY3NzYxNTQxMywiZXhwIjoxNjc3OTc1NDEzfQ.yUXkj6fgPNZqnktxXeF6T9SIlkbplnysvSQObVqtW_HYv6Cen1KCPqmw-L7menbb2PXwbzpqtKq7vlKcsLEmMg
Content-Type: application/json

{ "title":"Programador Java",
  "description":"buenas",
  "image":"",
  "country":"Colombia",
  "work_place":"Presencial",
  "working_day":" Full-time",
  "company_name":"La Favorita",
  "tecnologies_job": [
    {"id_tecno":1,"years":1}
    ,
    {"id_tecno":2,"years":2}
    ,
    {"id_tecno":3,"years":3}
    ],
  "rol_job_id":1,
  "job_salary": {"price":600}
}

### GET JOBS Get all Jobs with pagination
GET https://jobsapi-wtcn.onrender.com/api/v1/jobs?page=0&size=25


### GET JOBS Application
GET https://jobsapi-wtcn.onrender.com/api/v1/postulation/user?page=0&size=1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ0dXRhZ3VhcmFkaWdpdGFsQGdtYWlsLmNvbSIsImlhdCI6MTY3NzYxNTQxMywiZXhwIjoxNjc3OTc1NDEzfQ.yUXkj6fgPNZqnktxXeF6T9SIlkbplnysvSQObVqtW_HYv6Cen1KCPqmw-L7menbb2PXwbzpqtKq7vlKcsLEmMg
Content-Type: application/json

### Get un trabajo en particular
GET https://jobsapi-wtcn.onrender.com/api/v1/jobs/2



### requerimiento para los roles y las tecnologias relacionadas
GET https://jobsapi-wtcn.onrender.com/api/v1/rol



###
GET https://backapijobs-production-ad45.up.railway.app/api/v1/rol

### todas las postulaciones de un usuario
https://jobsapi-wtcn.onrender.com/api/v1/postulation/user
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzaHVsdHoxMkBnbWFpbC5jb20iLCJpYXQiOjE2NzY0MjU1MTMsImV4cCI6MTY3Njc4NTUxM30.kXVJaLRIe51BgyJsII_X-BL4JLIcI-Gd1FIy9lzZzS0QP5O_x9SglOM496_rXGhBvMYjOEvXtvNZJ4OTSNjCtg
Content-Type: application/json

### todas las tecnologias
GET https://jobsapi-wtcn.onrender.com/api/v1/tecnology
Content-Type: application/json

### eliminar una tecnologia
DELETE https://backapijobs-production-ad45.up.railway.app/api/v1/tecnology/18
Content-Type: application/json


### crear tecnologias
POST https://jobsapi-wtcn.onrender.com/api/v1/tecnology
Content-Type: application/json

{
"name":"TypeScript" 
} 

### crear rol
POST https://jobsapi-wtcn.onrender.com/api/v1/rol
Content-Type: application/json

{
"name":"Data Base Adminitrator" 
} 


### crear tecnologia asociada a un rol
POST https://jobsapi-wtcn.onrender.com/api/v1/rol_and_tecnology
Content-Type: application/json

{
  "rol_id":2,
  "tecnology_id":[1,3,7,8,9,10,11]
}


